project:
  type: website
  output-dir: docs

website:
  title: "Mapping and Spatial Analysis in R"
  site-url: https://yangjustinc.github.io/2025-mapping-and-spatial-analysis-in-r/

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
    code-fold: show
    code-tools: true
    code-copy: true
    number-sections: true
    css: styles.css

execute:
  warning: false
  message: false
  cache: true

bibliography: references.bib

# ensure these files are copied into docs/
resources:
  - styles.css
  - references.bib
